### ISSUE TITLE
[Bug]  My Bank app refuse to work with Smartspacer enabled

### ISSUE THREAD

**Issue by chjohans** [KieronQuinn/Smartspacer#110]
### Description

My bank app refuses to authorize any transaction when Smartspacer is enabled. More specifically, when "Smartspacer Widget Service" is enabled under accessibility settings. As I have understood it, this is necessary for Smartspacer to keep the widget updated.

My bank refused to reveal what is triggering the "ant-fraud code" in their app, but I am pretty sure it's the fact that the widget has been enabled in accessibility settings and the fact that it's an unknown app not installed from any app store.

The same issue is not present with other apps installed from the Google App Store that also have been enabled under accessibility settings.

My bank app works just fine if I disable accessibility settings for Smartspacer.

I have to agree with my bank on this one, it *is* rather suspicious when an unknown app can read everything on your screen, so I can see why they would refuse to authorize any transactions when this is the case.

Do you have any solution for this? Maybe you could consider to list Smartspacer through the Google app store?

**Comment by KieronQuinn** [comment]
Smartspacer cannot be on Google Play, ironically partially for the exact reason that's causing this issue (they don't allow accessibility services for what it uses them for). It's used to track which app is open, that's all.

As for your issue, you can maybe try reinstalling it over ADB using the -i flag and specifying com.android.vending as the package. https://stackoverflow.com/a/26272850

If that doesn't work, there's nothing I can do. Smartspacer cannot be on the Play Store and I don't control the stupid decisions of banking apps.

**Comment by chjohans** [comment]
Thanks, I'll try what you suggested.

Re those "stupid" bank apps, I'm not sure that I agree that they're exactly "stupid". It *is* a big red flag when an unknown app can read anything on the screen. Granted, in this case, I trust the application in question and I can even read the source code, but the bank does not know that! :)

Speaking of Google's policy not to allow apps in their app store that use accessibility services this way. "Cube ACR" is another example, they are still on the app store but to get the version that allows use of the accessibility service you have to download a separate version of it's "connector" from their website, this can be done through their app. This approach does not trigger my banking the same way as Smartspacer does. But I do understand that you are doing this for free in your spare time so I don't expect you to go through a lot of trouble for this to work as I might be a unique use case. But technically you could have a version of your app that adheres to Google's requirements in the app store, and then let your app update itself from your website.

Too bad, as the Google At-A-Glance has some issues on my Galaxy S23 Ultra and this worked perfectly, that is until I ran into the banking app issue.

Q: The help text in your app suggests that updating the widget works even without the accessibility service being enabled, at the cost of a higher battery usage. Is that correct?

**Comment by KieronQuinn** [comment]
It may do, but I can't guarantee anything. At the very least it will be much less battery efficient like you say.

Accessibility blocking is a fad. It's the same faux security they used to pull by blocking screenshots, before realising users want to take screenshots of their account. It's "stupid" because they cannot and don't implement the same blocks on the websites, it's just because someone has suggested it's a risk they can manage, when in fact it's the OS which has this responsibility (and already does implement blocks, that's what restricted settings do). They shouldn't be doing it, and I hope it gets ruled against when Google eventually get around to looking at it for the Play Developer Terms. 

Regardless, publishing to Play is a minefield and a suspension would make me lose my job, so I'm not doing it. Accessibility is only one of the risks.

**Comment by KieronQuinn** [comment]
I further evaluated this for 1.4.3, and have discovered that since Android 11, it's now possible to get the package that first installed the app, and ADB install cannot override that. That means, if the bank app is using that field, it's impossible to get around this restriction (even with root). 

Publishing to Google Play is as I said unviable, so if the ADB method doesn't work then nothing can be done at all.

**Comment by chjohans** [comment]
Thanks for your effort with this. The adb method of installing made no difference. But it seems like your Plugin works just fine, and is updating, without enabling it in accessibility settings.
