### ISSUE TITLE
Widget Pages - Vertical Swiping/better toggle between pages

### ISSUE THREAD

**Issue by jmoore-rundeck** [KieronQuinn/Smartspacer#176]
### Suggestion

I realize widgets cannot be used to swipe through each Smartspacer target or complication, but it works perfectly on the lock screen (swiping through each page). I think it would be great if Spartspacer could have a home screen widget setting to make it easier to cycle between your pages. The small dots are too small and I can never cycle back to the far left page

**Comment by KieronQuinn** [comment]
Multiple targets on the widget at once will not be done due to issues around knowing which ones are visible (widgets do not have the ability to report that back to the app). This would introduce significant performance and battery issues around frequency of updating the widget.

In addition, the way widgets work with lists makes the handling of tap events much more difficult, increasing the complexity significantly.

This may become more of a viable option in the future with Jetpack Glance, but at the moment I do not consider Glance as a stable option for a production app so it's not going to happen just yet.
