### ISSUE TITLE
[Bug] SmartSpacer does not display using Native and OEM Mode on high grid sizes

### ISSUE THREAD

**Issue by DexTheExplorer** [KieronQuinn/Smartspacer#25]
### Description

The Smartspacer blanks out when setting the grid to 5x7 or higher, whereas the preview inside the Look & Feel app shows the default Pixel space fine.

5x6 scaling
![Screenshot_20231101-122248_Hintergrund_ _Stil](https://github.com/KieronQuinn/Smartspacer/assets/67872150/ba7c20a2-f4b7-469f-b37d-ff2e25e718e2)
![Screenshot_20231101-122235](https://github.com/KieronQuinn/Smartspacer/assets/67872150/fc72f46a-34de-4c62-9fe6-393d39ee497d)

5x7+ scaling
![Screenshot_20231101-122251_Hintergrund_ _Stil](https://github.com/KieronQuinn/Smartspacer/assets/67872150/aff215e7-267d-4b3f-afb0-aed6a5aeb6a7)
![Screenshot_20231101-122255_Paranoid_Launcher](https://github.com/KieronQuinn/Smartspacer/assets/67872150/de448dd5-1089-4c18-b92e-572a606fe3e3)

When trying to place a widget or an app icon in the seemingly blank space, you can see that it's still occupied by the invisible Smartspacer
![Screenshot_20231101-122301_Paranoid_Launcher](https://github.com/KieronQuinn/Smartspacer/assets/67872150/b5fdf0de-6a01-42ac-8174-1c32f8c161bb)

This issue persists reboots and turning off Smartspacer makes the stock At A Glance reappear, which displays fine

**Comment by KieronQuinn** [comment]
I can't reproduce this with a custom modified version of the Pixel Launcher (using the XML from Pixel Launcher Extended since it's not compatible with 14), so I'm going to have to assume it's an incompatibility with another PLE mod. If it ever gets updated to support 14 and I can reproduce it, I can maybe look to fix it, but for now there's nothing that can be done.
