### ISSUE TITLE
[Bug] Android 15's Private space create/remove/block/unblock unbinds Smartspacer from At A Glance

### ISSUE THREAD

**Issue by paulkugaev** [KieronQuinn/Smartspacer#257]
### Description

As title says, every time Private space is blocked and unblocked Smartspacer shows a notification that it has been disconnected from At A Glance. The same behavior is observed when creating and removing Private space

**Comment by GittyMac** [comment]
This seems to be related to profiles in general as pausing Work apps also causes a disconnect.

**Comment by KieronQuinn** [comment]
It's a genuine disconnect unfortunately (not a false positive), so there's nothing I can do.

**Comment by stek29** [comment]
I believe it is in fact a false disconnect detection rather than Smartspacer actually being unbound from At A Glance.

Private Space and Work Profile are separate Android users. When one of them is stopped, `com.google.android.as` (ASI) running for that user is also killed. Smartspacer’s "IProcessObserver" sees that process death, but it currently only checks the package name:

https://github.com/KieronQuinn/Smartspacer/blob/1cbe0a229a0379f2e8e7e6a1a2a5f506211736a2/app/src/main/java/com/kieronquinn/app/smartspacer/service/SmartspacerShizukuService.kt#L478-L486

I tested this with a local patched build that added more logging around this path:

```
 private fun setupCrashListener() = scope.launch {
     activityManager.processDied().collect { uid ->
         if(suppressCrash) return@collect
+        val userId = uid / 100000
+        val myUserId = getUserId()
         val packages = packageManager.getPackagesForUid(uid) ?: return@collect
+        Log.d(TAG, "processDied uid=$uid user=$userId myUser=$myUserId packages=${packages.joinToString()}")
         packages.forEach { pkg ->
            onPackageDied(pkg)
         }
     }
 }
```

The logs showed Smartspacer observing ASI deaths from secondary users `user=11` and `user=12`, while Smartspacer itself was running as `myUser=0`.

Also, judging from AOSP, Smartspace service/cache state is keyed by Android user ID. `SmartspaceManagerService` is backed by `SmartspacePerUserService`, and `AbstractMasterSystemService.onUserStopped()` removes only the cached service for `user.getUserIdentifier()`, via `removeCachedServiceListLocked(userId)`, which deletes only `mServicesCacheList.delete(userId)`.

The temporary service override is also user-scoped: `ServiceNameBaseResolver` documents `mTemporaryServiceNamesList` as keyed by `userId`, and stores it as `mTemporaryServiceNamesList.put(userId, componentNames)`.

I then tested filtering by Android user before calling `onAsiStopped()`, something like this:

```
if(packageName == PACKAGE_ASI) {
    if(userId != myUserId) {
        return
    }
    crashListener?.onAsiStopped()
}
```

With that change, ASI deaths from Work Profile / Private Space users were correctly ignored and the reconnect notification stopped appearing during those toggles, while the existing reconnect path should still work for a real ASI death in the current user.

And more importantly, even on the unpatched version, after the reconnect notification appears, Smartspacer still appears to keep working and stay connected.
