### ISSUE TITLE
Smartspacer recommends installing older version [Bug] 

### ISSUE THREAD

**Issue by eliasacab** [KieronQuinn/Smartspacer#55]
### Description

Manually updated to version 1.3 by downloading from GitHub and when I opened the app, it said there was an "update" available: version 1.2.2. I understand that the update perhaps hadn't been sent to the app yet, hence the manual update, but maybe if the installed version number is greater than the latest update available from within the app, then it shouldn't pop up? Thanks!

**Comment by KieronQuinn** [comment]
You likely got served a GitHub cached version, [the API isn't returning 1.3 yet](https://api.github.com/repos/KieronQuinn/Smartspacer/releases). I usually don't do mentions on release for this reason, because it can take GitHub a few minutes to update caches, but in this case it was required due to the crash.
