### ISSUE TITLE
[Suggestion] custom time for showing calendar events

### ISSUE THREAD

**Issue by realmenwearpink2** [KieronQuinn/Smartspacer#82]
### Suggestion

Having the ability to show a calendar event 12hrs, 15hrs, 24hrs or other custom timeframe before event would be nice

**Comment by KieronQuinn** [comment]
This would unfortunately cause a significant battery drain, it's bad enough updating with an alarm every minute for the time period before that already exists (which was extended by request), adding more is just asking for trouble.

**Comment by e-t-l** [comment]
@KieronQuinn I've looked through the source code but can't figure it out, why does the calendar target require an alarm every minute? If the time range is set to the maximum 2 hours, when exactly is the 2-hour period that's filled with alarms? 

Surely, SmartSpacer just fetches the calendar data for the upcoming two hours whenever SmartSpacer's widget refreshes? ...Are you saying that the only way to fetch calendar data is to populate the calendar with alarms?

**Comment by e-t-l** [comment]
...or is the purpose of the timers to trigger the widget refresh, so that the text "...in X minutes" is always accurate?

If that is the case, I would actually be happy with an option to DISABLE the "...in X minutes" text completely. The calendar target already shows the start time of the event; I don't need it to also show me a countdown.

(My main use of SmartSpacer is to easily check in the morning what my \*first\* scheduled event is that day. So, I need it to show me events that might be 8+ hours away! But I certainly \*don't \* need to see a live countdown to that event.

So ideally, the calendar target should have event range options for "until midnight," or at least "in the next 24hrs." There should be a toggle to show/hide the countdown timer, and either it's automatically disabled for ranges greater than 2 hours, or it has a label like: "Warning! This feature may cause extreme battery drain."

@KieronQuinn might that be reasonable?

**Comment by KieronQuinn** [comment]
The alarm is used to refresh the text yes. It is perhaps something that could be optional though.
