### ISSUE TITLE
[Bug] Re-enable loop

### ISSUE THREAD

**Issue by kennyeni** [KieronQuinn/Smartspacer#93]
### Description

Hi,

For the last couple days I have experienced Smartspacer looping on the "enable notification".

This happened with the previous version as well, so I upgraded and it still hasn't resolved. The app even says it detected a feedback loop when starting and gives the option to retry.

I have the analytics option enabled, but let me know if you prefer me to make a dump.

I'm on pixel 8 pro, all latest updates and using Sui.

Thanks!

**Comment by KieronQuinn** [comment]
The only time this happens is when there is a genuine feedback loop, since it can only be triggered by the app connecting to itself. This means the Native Smartspace service is not being cleared to allow reconnection to the system one.

There's two possible fixes you can try:

- Disable Native Smartspace, force stop Smartspacer, wait 60 seconds then relaunch and re-enable Native Smartspace
- Reboot

Note that the delay is a genuine requirement, I'm not just making you wait for nothing - there's a flag in the system that clears after that period. If neither of these work, then there's nothing I can really do and only reinstalling may fix it.
